spring:
  profiles:
    active: dev
  liquibase:
    enabled: true
    change-log: "classpath:/liquibase/changelog-master.xml"
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR